name: Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'gradle'
      - run: chmod -R 700 ./
      - name: Run build with Gradle wrapper
        run: ./gradlew build --scan
      - uses: actions/upload-artifact@v3
        with:
          name: builds
          path: build/libs/

