name: Integration

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'gradle'
      - run: chmod -R 700 ./
      - uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1